# Generated by Django 5.1.5 on 2025-01-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
